[package]
name = "minecraft_downloader_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
requests_rs = "0.1.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"